# A service with a cluster IP that serves as a load-balancer for the textindexer.
apiVersion: v1
kind: Service
metadata:
  name: services-textindexer
  namespace: services-data
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: grpc
  selector:
    app: services-textindexer-instance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-textindexer-instance
  namespace: services-data
  labels:
    app: services-textindexer-instance
spec:
  selector:
    matchLabels:
      app: services-textindexer-instance
  replicas: 2
  template:
    metadata:
      labels:
        app: services-textindexer-instance
        role: data-api
    spec:
      containers:
      - name: services-textindexer
        imagePullPolicy: Always
        image: localhost:5000/services-textindexer:latest
        args:
          - "-text-indexer-uri=es://elasticsearch-master.services-data:9200"
        ports:
        - containerPort: 8080
          name: grpc
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 50m
